# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gloomstone_sentinel/animations/open_loop/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.open_loop.frame 1