# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gloomstone_sentinel.root] run return 0
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.data] unless data entity @s {data:{rigHash: '654bc8af3e5681f6e0b7f9ca1a9530736e60a6573d1a95e7ca5818f1e25eed35'}} on vehicle run function animated_java:gloomstone_sentinel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1