# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.open_loop.frame dummy
execute as @e[type=item_display,tag=aj.gloomstone_sentinel.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:gloomstone_sentinel/root/on_load