# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.gloomstone_sentinel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gloomstone_sentinel', 'function_path': 'animated_java:gloomstone_sentinel/variants/default/apply'}
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_rb] run function animated_java:gloomstone_sentinel/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_rf] run function animated_java:gloomstone_sentinel/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_lb] run function animated_java:gloomstone_sentinel/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_lf] run function animated_java:gloomstone_sentinel/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.gem] run function animated_java:gloomstone_sentinel/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.pupil] run function animated_java:gloomstone_sentinel/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.eye] run function animated_java:gloomstone_sentinel/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.head] run function animated_java:gloomstone_sentinel/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.upper_shell] run function animated_java:gloomstone_sentinel/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.body] run function animated_java:gloomstone_sentinel/variants/default/zzz/9