# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_rb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_rb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_rf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_rf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_lb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_lb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.leg_lf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_lf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.gem] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_gem set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.pupil] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_pupil set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.eye] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_eye set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.upper_shell] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_upper_shell set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.gloomstone_sentinel.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out