# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.gloomstone_sentinel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gloomstone_sentinel', 'function_path': 'animated_java:gloomstone_sentinel/animations/open_loop/next_frame'}
execute if score @s aj.open_loop.frame matches 41.. run scoreboard players set @s aj.open_loop.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.open_loop.frame
execute at @s run function animated_java:gloomstone_sentinel/animations/open_loop/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.open_loop.frame 1