# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.gloomstone_sentinel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gloomstone_sentinel', 'function_path': 'animated_java:gloomstone_sentinel/animations/open_loop/stop'}
tag @s remove aj.gloomstone_sentinel.animation.open_loop.playing
scoreboard players set @s aj.open_loop.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:gloomstone_sentinel/animations/open_loop/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only